name: Release
on:
  workflow_dispatch:
jobs:
  package:
    uses: ./.github/workflows/reusable-package.yml
  release:
    needs: package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Download artifacts
        uses: actions/download-artifact@v4
      - name: Create release
        run: |
          cd LuaJIT || exit 1
          VERSION="2.1"
          git checkout "v${VERSION}"
          COMMIT_TIME_SECONDS=$(git show -s --format=%ct)
          COMMIT_TIME_DAYS=$((COMMIT_TIME / 60 / 60 / 24))
          cd .. || exit 2
          gh release create "v${VERSION}.${COMMIT_TIME_DAYS}" --notes "LuaJIT ${VERSION}.${COMMIT_TIME_SECONDS}" ./build/*.msi ./build/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
