name: Release
on:
  workflow_dispatch:
jobs:
  package:
    uses: ./.github/workflows/reusable-package.yml
  release:
    needs: package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Download artifacts
        uses: actions/download-artifact@v3
      - name: Create release
        run: |
          cd LuaJIT || exit 1
          git checkout v2.1
          COMMIT_TIME=$(git show -s --format=%ct)
          DAYS=$((COMMIT_TIME / 60 / 60 / 24))
          TAG="v2.1.${DAYS}"
          cd .. || exit 2
          gh release create "${TAG}" --notes "LuaJIT ${TAG}" ./build/*.msi ./build/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
