name: Reusable package
on:
  workflow_call:
jobs:
  package:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Package
        shell: pwsh
        run: |
          function Start-VsDevCmd {
            $installationPath = (
                & "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe" `
                    -prerelease -latest -property installationPath)
            $vsdevcmd = Join-Path `
                -Path "$installationPath" `
                -ChildPath Common7\Tools\VsDevCmd.bat `
                -Resolve
            & "${env:COMSPEC}" /s /c "`"$vsdevcmd`" -no_logo -arch=amd64 && set" |
                ForEach-Object {
                  $name, $value = $_ -split '=', 2
                  Set-Content env:\"$name" $value
                }
          }
          Start-VsDevCmd
          cmake -B build -G Ninja -D CMAKE_C_COMPILER=cl
          cmake --build build --target package
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: |
            build/*.msi
            build/*.zip
          if-no-files-found: error
