name: Reusable package
on:
  workflow_call:
jobs:
  package:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Package
        shell: pwsh
        run: ./Build-LuaJIT.ps1
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: |
            build/*.msi
            build/*.zip
          if-no-files-found: error
